src/config/routes.rb
Rails.application.routes.draw do

  resources :campaigns
  resources :journal_entries
  resources :characters
  resources :campaigns
  resources :fonts
  resources :characters
  resources :campaigns
  resources :journal_entries

  devise_for :users
  get 'accueil/index'

  root 'accueil#index'
end

src/app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
end

src/app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :set_journal_entry, only: [:show, :edit, :update, :destroy]

  # GET /journal_entries
  # GET /journal_entries.json
  def index
    @journal_entries = JournalEntry.all
  end

  # GET /journal_entries/1
  # GET /journal_entries/1.json
  def show
  end

  # GET /journal_entries/new
  def new
    @journal_entry = JournalEntry.new
  end

  # GET /journal_entries/1/edit
  def edit
  end

  # POST /journal_entries
  # POST /journal_entries.json
  def create
    @journal_entry = JournalEntry.new(journal_entry_params)

    respond_to do |format|
      if @journal_entry.save
        format.html { redirect_to @journal_entry, notice: 'Journal entry was successfully created.' }
        format.json { render :show, status: :created, location: @journal_entry }
      else
        format.html { render :new }
        format.json { render json: @journal_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journal_entries/1
  # PATCH/PUT /journal_entries/1.json
  def update
    respond_to do |format|
      if @journal_entry.update(journal_entry_params)
        format.html { redirect_to @journal_entry, notice: 'Journal entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal_entry }
      else
        format.html { render :edit }
        format.json { render json: @journal_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journal_entries/1
  # DELETE /journal_entries/1.json
  def destroy
    @journal_entry.destroy
    respond_to do |format|
      format.html { redirect_to journal_entries_url, notice: 'Journal entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal_entry
      @journal_entry = JournalEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_entry_params
      params[:journal_entry]
    end
end

src/app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

src/app/views/journal_entries/_form.html.erb
<%= form_for(@journal_entry) do |f| %>
  <% if @journal_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal_entry.errors.count, "error") %> prohibited this journal_entry from being saved:</h2>

      <ul>
      <% @journal_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/journal_entries/edit.html.erb
<h1>Editing Journal Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @journal_entry %> |
<%= link_to 'Back', journal_entries_path %>

src/app/views/journal_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Journal Entries</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journal_entries.each do |journal_entry| %>
      <tr>
        <td><%= link_to 'Show', journal_entry %></td>
        <td><%= link_to 'Edit', edit_journal_entry_path(journal_entry) %></td>
        <td><%= link_to 'Destroy', journal_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Journal entry', new_journal_entry_path %>

src/app/views/journal_entries/new.html.erb
<h1>New Journal Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', journal_entries_path %>

src/app/views/journal_entries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_journal_entry_path(@journal_entry) %> |
<%= link_to 'Back', journal_entries_path %>