src/config/routes.rb
Rails.application.routes.draw do

  resources :campaigns
  resources :journal_entries
  resources :characters
  resources :campaigns
  resources :fonts
  resources :characters
  resources :campaigns
  resources :journal_entries

  devise_for :users
  get 'accueil/index'

  root 'accueil#index'
end

src/app/models/campaign.rb
class Campaign < ActiveRecord::Base
end

src/app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params[:campaign]
    end
end

src/app/helpers/campaigns_helper.rb
module CampaignsHelper
end

src/app/views/campaigns/_form.html.erb
<%= form_for(@campaign) do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% @campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

src/app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Campaigns</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= link_to 'Show', campaign %></td>
        <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
        <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign', new_campaign_path %>

src/app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form' %>

<%= link_to 'Back', campaigns_path %>

src/app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>